exp_name: "fno_control"
gpu: 0
seed: 0
results_path: "./results/002-control_cylinder/"

# data
dataset_name: "controlled_cylinder"
dataset_root: "./dataset/"
use_hf_dataset: true
num_workers: 4
normalizer: "gaussian" # none, gaussian, range

# data parameters for training
mask_prob: 0.1
noise_scale: 0.1 # only applicable for numerical data

# model
model_name: "fno"
checkpoint_path:  # fill in to resume training
modes1: 4
modes2: 12
modes3: 16
n_layers: 4
width: 64

# training
is_use_tb: True
scheduler: cosine # step, cosine
step_size: 1000 # only applicable for step scheduler
num_update: 4000
train_batch_size: 16
test_batch_size: 32
lr: 0.0001
clip_grad_norm: 0.

# evaluation
N_autoregressive: 1
N_plot: 0