exp_name: "deeponet_cylinder_ablation_tau0.99"
gpu: 3
seed: 0
results_path: "./results/001-cylinder/"

# data
dataset_name: "cylinder"
dataset_root: "./data/realpdebench/"
use_hf_dataset: true
num_workers: 32
normalizer: "gaussian"

# data parameters for training
train_data_type: "real"
mask_prob: 0.1
noise_scale: 0.0

# model
model_name: "deeponet"
checkpoint_path: ./results/001-cylinder/deeponet/deeponet_cylinder_pretrained/2026-03-12_11-16-03/model_5000.pth
p: 128
dropout_rate: 0.1

# training
is_use_tb:
scheduler: cosine
step_size: 1000
num_update: 4000
train_batch_size: 4
test_batch_size: 8
lr: 0.0001
clip_grad_norm: 0.

# evaluation
N_autoregressive: 10
N_plot: 0
probe_diagnostic: True
N_plot_probe: 12

# null-space fine-tuning specific
ns_n_components: 200
ns_variance_threshold: 0.99
ns_alpha: 1.0
ns_progressive: false
ns_beta_min: 0.3
ns_layer_wise: true
ns_max_samples: 200
ns_projection_path:
