exp_name: "deeponet_combustion"
gpu: [0, 1]
seed: 0
results_path: "./results/003-combustion/"

# data
dataset_name: "combustion"
dataset_root: "./data/realpdebench/"
use_hf_dataset: true
num_workers: 4
normalizer: "gaussian"

# data parameters for training
train_data_type: "real"
mask_prob: 0.1
noise_scale: 0.0

# model
model_name: "deeponet"
checkpoint_path: ./results/003-combustion/deeponet/deeponet_combustion_pretrained/2026-03-21_10-20-54/model_0960.pth
p: 128
dropout_rate: 0.1

# training
is_use_tb:
scheduler: cosine
step_size: 1000
num_update: 4000
train_batch_size: 4
test_batch_size: 8
lr: 0.0001
clip_grad_norm: 0.

# evaluation
N_autoregressive: 1
N_plot: 0
probe_diagnostic: True
N_plot_probe: 12

# null-space fine-tuning specific
ns_n_components: 200
ns_variance_threshold: 0.5
ns_alpha: 0.3
ns_progressive: true
ns_beta_min: 0.1
ns_layer_wise: true
ns_max_samples: 200
ns_projection_path:
