exp_name: "fno_combustion"
gpu: 0
seed: 0
results_path: "./results/003-combustion/"

# data
dataset_name: "combustion"
dataset_root: "./data/realpdebench/"
use_hf_dataset: true
num_workers: 4
normalizer: "gaussian"

# data parameters for training
train_data_type: "real"
mask_prob: 0.1
noise_scale: 0.1  # extra noise injected to amplify sim-to-real distribution shift (physical-forgetting experiment)

# model
model_name: "fno"
checkpoint_path: ./results/003-combustion/fno/fno_combustion_pretrained/2026-03-20_11-54-28/model_1000.pth
modes1: 4
modes2: 16
modes3: 16
n_layers: 4
width: 64

# training
is_use_tb:
scheduler: cosine
step_size: 1000
num_update: 4000
train_batch_size: 4
test_batch_size: 8
lr: 0.0001
clip_grad_norm: 0.

# evaluation
N_autoregressive: 1
N_plot: 0
probe_diagnostic: True
N_plot_probe: 12
